// Generated by CoffeeScript 1.10.0
(function() {
  var DOMListener;

  DOMListener = (function() {
    var _lastBodyMD5;

    _lastBodyMD5 = null;

    function DOMListener() {
      this._oblique = Oblique();
      jQuery(document).ready((function(_this) {
        return function() {
          _this._lastBodyMD5 = _this._InnerHtmlMD5();
          _this._checkDOMChanged();
          return _this._oblique.notify("oblique.dom_ready");
        };
      })(this));
    }

    DOMListener.prototype._InnerHtmlMD5 = function() {
      var documentBody;
      documentBody = document.body;
      if (documentBody === null) {
        return "";
      }
      return md5(documentBody.innerHTML);
    };

    DOMListener.prototype._checkDOMChanged = function() {
      var bodyHashChangedSinceLastTime, newBodyMD5;
      newBodyMD5 = this._InnerHtmlMD5();
      bodyHashChangedSinceLastTime = newBodyMD5 !== this._lastBodyMD5;
      if (bodyHashChangedSinceLastTime) {
        this._oblique.notify("oblique.dom_changed");
      }
      this._lastBodyMD5 = newBodyMD5;
      return setTimeout((function(_this) {
        return function() {
          return _this._checkDOMChanged();
        };
      })(this), 200);
    };

    return DOMListener;

  })();

  window.DOMListener = DOMListener;

}).call(this);
