// Generated by CoffeeScript 1.10.0
(function() {
  this.DOMReadyListener = (function() {
    var addDocumentLoadEventListener, completed, ready, removeDocumentLoadEventListener;

    addDocumentLoadEventListener = function() {
      document.addEventListener('DOMContentLoaded', completed);
      return window.addEventListener('load', completed);
    };

    removeDocumentLoadEventListener = function() {
      document.removeEventListener('DOMContentLoaded', completed);
      return window.removeEventListener('load', completed);
    };

    ready = function() {
      return setTimeout(function() {
        return Oblique().notify("ready.ob.dom");
      }, 0);
    };

    completed = function() {
      ready();
      return removeDocumentLoadEventListener();
    };

    function DOMReadyListener() {
      if (this.documentIsReady()) {
        ready();
        return;
      }
      addDocumentLoadEventListener();
    }

    DOMReadyListener.prototype.documentIsReady = function() {
      var isComplete, isLoading, isScrolling, readyState;
      readyState = document.readyState;
      isScrolling = document.documentElement.doScroll;
      isComplete = readyState === 'complete';
      isLoading = readyState === 'loading';
      if (isComplete) {
        return true;
      }
      if ((!isLoading) && (!isScrolling)) {
        return true;
      }
      return false;
    };

    return DOMReadyListener;

  })();

}).call(this);
