// Generated by CoffeeScript 1.10.0
(function() {
  this.Events = (function() {
    function Events() {}

    Events.domReady = "ready.ob.dom";

    Events.domChanged = "changed.ob.dom";

    return Events;

  })();

}).call(this);
