// Generated by CoffeeScript 1.10.0
(function() {
  this.Oblique = (function() {
    function Oblique() {
      if (this === window) {
        return new Oblique();
      }
      if (Oblique._singletonInstance) {
        return Oblique._singletonInstance;
      }
      Oblique._singletonInstance = this;
      this._EventBus = new EventBus();
      this._DOMReadyListener = new DOMReadyListener();
    }

    Oblique.prototype.on = function(eventName, eventHandler) {
      return this._EventBus.on(eventName, eventHandler);
    };

    Oblique.prototype.notify = function(eventName, eventData) {
      return this._EventBus.notify(eventName, eventData);
    };

    Oblique.prototype.destroy = function() {
      return Oblique._singletonInstance = void 0;
    };

    return Oblique;

  })();

}).call(this);
